<?php
function clean($string) {
	$string = html_entity_decode(preg_replace('/&([a-zA-Z]{1,2})(?:acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);/i', '$1', htmlentities($string, ENT_QUOTES, 'UTF-8')), ENT_QUOTES, 'UTF-8');
	$string = strtolower(trim(preg_replace('/[^0-9a-z]+/i', '-', $string), '-'));

	return $string;
}
$arrayNames = array('Achæos',
'Achéloos',
'Achille',
'Acis',
'Acrisios',
'Actéon',
'Adonis',
'AEson',
'AEthra',
'AEtolos',
'Agamemnon',
'Agénor',
'Age d’or',
'Age d’argent',
'Age héroïque',
'Age d’Airin',
'Age de Fer',
'Aiétès',
'Ajax [le Grand]',
'Ajax [le Petit]',
'Alcmène [la Forte]',
'Aloades',
'Amalthée',
'Amazones',
'Amphitrite',
'Amphitryon',
'Amycos',
'Anchise',
'Androgée',
'Andromède',
'Antée',
'Antigone-fille de Laomédon',
'Antigone-fille d’OEdipe',
'Antiope-fille d’Arès',
'Antiope-fille d’Asopos',
'Aphrodite',
'Apollon',
'Arès',
'Aréopage',
'Argonautes',
'Argos-fils de Zeus',
'Argos-l’argonaute',
'Argos-panoptes',
'Ariane',
'Aristée',
'Artémis',
'Asclépios',
'Asopos',
'Astéria',
'Atalante',
'Athéna',
'Atlas',
'Atrée',
'Atrides',
'Augias',
'Bacchantes',
'Bellérophon',
'Borée',
'Briséis',
'Cadmos',
'Calliope',
'Callisto',
'Cassandre',
'Castor et Pollux',
'Cécrops',
'Centaures',
'Cerbère',
'Chalcas',
'Chaos',
'Charites',
'Charon',
'Charybde et Scylla',
'Chimère',
'Chiron',
'Chryséis',
'Circé',
'Clymène',
'Clytemnestre',
'Créüse-princesse athénienne-',
'Créüse-princesse corinthienne-',
'Créüse-princesse troyenne-',
'Créon-roi de Corinthe-',
'Créon-[roi de Thèbes]',
'Cronos',
'Cyclopes',
'Cycnos-fils d Apollon-',
'Cycnos-fils d Arès-',
'Cycnos-fils de Poséidon-',
'Cycnos-roi de Ligurie-',
'Cyparissos',
'Cyrène',
'Danaé',
'Danaïdes',
'Danaos',
'Daphné',
'Dédale',
'Déjanire',
'Déluge',
'Démèter',
'Deucalion',
'Dieu fleuve',
'Diogène-de Sinope-',
'Diomède-fils d Arès-',
'Diomède-fils de Tydée-',
'Dioné',
'Dionysos',
'Doris',
'Dryope',
'Eaque',
'Echidna',
'Echo',
'Egée',
'Enée',
'Endymion',
'Enfers',
'Eole-fils d Hellen-',
'Eole-fils de Poséidon, Gardien des vents-',
'Eos',
'Epaphos',
'Epiméthée',
'Erèbe',
'Erechthée',
'Erichthonios',
'Erinyes',
'Eris',
'Eros',
'Euphémos',
'Europe',
'Eurysthée',
'Gaia',
'Galatée',
'Ganymède',
'Géants',
'Géryon',
'Gorgones',
'Grées',
'Hadès',
'Halirrhotios',
'Harmonie',
'Harpocrate',
'Harpyies',
'Hébé',
'Hécate',
'Hécatonchires',
'Hécube',
'Hélène',
'Héliades',
'Hélios',
'Héphaistos',
'Héra',
'Héraclès',
'Héraclès-[Les Douze travaux]',
'Hésiode',
'Hésione-[princesse troyenne]',
'Hector',
'Hellen',
'Hermaphrodite',
'Hermès',
'Hermès-[Trismégiste]',
'Hermione',
'Hespérides',
'Hestia',
'Hippodamie',
'Hippolyte-[fils de Thésée]',
'Hippolyte-[reine des Amazones]',
'Homère',
'Hores',
'Hyacinthos',
'Hyades',
'Hydre de Lerne',
'Hypérion',
'Inachos',
'Io',
'Ion',
'Iphigénie',
'Iris',
'Ixion',
'Janus',
'Japet',
'Jason',
'Jeux olympiques',
'Kères',
'Laïos',
'Labdacides',
'Labyrinthe',
'Lacédœmon',
'laomedon',
'Léda',
'Léto',
'Linos',
'Maïa',
'Marsyas',
'Médée',
'Méduse',
'Méléagre',
'Ménélas',
'Ménétios',
'Métis',
'Midas',
'Minos',
'Minotaure',
'Mnémosyne',
'Moires',
'Molionides',
'Morphée',
'Muses',
'Myrmidons',
'Narcisse',
'Némésis',
'Nérée',
'Néréides',
'Nessus',
'Niobé fille de Phoronée',
'Niobé fille de Tantale',
'Nuit',
'Océan',
'Océanides',
'OEdipe',
'Oreste',
'Orion',
'Orphée',
'Ouranos',
'Ovide',
'Pan',
'Panathénées',
'Pandion-arrière-petit-fils de Pandion-',
'Pandion-fils d Erichthonios-',
'Pandore',
'Parnasse (Le Mont)',
'Pasiphaé',
'Patrocle',
'Pâris',
'Pégase',
'Pélée',
'Pélops',
'Pénélope',
'Persé',
'Persée',
'Perséphone',
'Phaéton',
'Phèdre',
'Phébé',
'Phidias',
'Phorcys',
'Pléiades',
'Polydecte',
'Polyphème',
'Pontos',
'Poséidon',
'Praxitèle',
'Priam',
'Procuste',
'Prométhée',
'Protée',
'Psyché',
'Pygmalion-roi de Tyr-',
'Pygmalion-sculpteur-',
'Pyrrha',
'Pyrrhos',
'Python-le Serpent-',
'Rhadamanthe',
'Rhéa',
'Rhodos',
'Satyres',
'Séléné',
'Sémélé',
'Silène',
'Silènes',
'Sirènes',
'Sisyphe',
'Socrate',
'Sphinx',
'Styx',
'Tantale',
'Télamon',
'Télémaque',
'Téthys',
'Terpsichore',
'Théia',
'Thémis',
'Thésée',
'Titanides',
'Titans',
'Toison d or',
'Triton',
'Troie',
'Troie-( La Guerre de Troie - Les personnages de l Iliade d Homère )',
'Troie-( Le cheval de Troie )',
'Tros',
'Tyndare',
'Typhon-fils d Héra-',
'Typhon-fils de Gaia-',
'Ulysse',
'Xuthos',
'Zéphyre',
'Zeus',
);
$liste = '';
$ecriture = '';
$handle = '';
foreach($arrayNames as $name) {
	if(is_file(clean($name).'.php')) {
		$file = clean($name).'.php';
		$liste .= '
		<a href="'.$file.'" title = "'.$file.'">'.$name.'</a>';
	} else {
		$ecriture =  '<?php 
		echo \'<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<title>Mythologie grecque (essai de lexique) - '.$name.'</title>
<link href="web/css/style.css" rel="stylesheet"></head>
<h1>'.$name.'</h1>
<a href="index.php">Home</a>
</body>
</html>
</div>
</body>
</html>\';
';
		$handle = fopen(clean($name).'.php', 'w+');
		@chmod(clean($name).'.php', 0777);
		@fwrite($handle, $ecriture);
		@fclose($handle);
	}
}
?>
<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<title>Mythologie grecque (essai de lexique) - Accueil</title>
<link href="web/css/style.css" rel="stylesheet"></head>
</head>
<h1>
<?php 
echo nl2br($liste); 
?>
</body>
</html>